prompts:
  - "a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand."
  # - "Some basil leaves in a container on a counter."
  # - "a person with a watch that is over a desk with a calendar"
  # - "a mac computer screen with a bottle covering part of the screen in the image"
  # - "a person is holding a small container of deodorant, the deodorant is branded by the company avon."
  # - "a black and white tag listing the specifics of a kitchenaid mixer."
  # - "top of a blue broth box that is currently closed."
  # - "a pink 70s style bathroom toilet and tub visible with blue bottles on the toilet tank"
  # - "a small dog with fluffy tail hair is walking on the patio outside her home near a food bowl."
  # - "a video conversion system cd in a paper packet with a laminated front covering."
  # - "round dial knob on a white washing machine"

  - "low quality picture of a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand."
  # - "low quality picture of Some basil leaves in a container on a counter."
  # - "low quality picture of a person with a watch that is over a desk with a calendar"
  # - "low quality picture of a mac computer screen with a bottle covering part of the screen in the image"
  # - "low quality picture of a person is holding a small container of deodorant, the deodorant is branded by the company avon."
  # - "low quality picture of a black and white tag listing the specifics of a kitchenaid mixer."
  # - "low quality picture of the top of a blue broth box that is currently closed."
  # - "low quality picture of a pink 70s style bathroom toilet and tub visible with blue bottles on the toilet tank"
  # - "low quality picture of a small dog with fluffy tail hair is walking on the patio outside her home near a food bowl."
  # - "low quality picture of a video conversion system cd in a paper packet with a laminated front covering."
  # - "low quality picture of a round dial knob on a white washing machine"
  
  - "a VizWiz style picture of a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand."
  # - "a VizWiz style picture of Some basil leaves in a container on a counter."
  # - "a VizWiz style picture of a person with a watch that is over a desk with a calendar"
  # - "a VizWiz style picture of a mac computer screen with a bottle covering part of the screen in the image"
  # - "a VizWiz style picture of a person is holding a small container of deodorant, the deodorant is branded by the company avon."
  # - "a VizWiz style picture of a black and white tag listing the specifics of a kitchenaid mixer."
  # - "a VizWiz style picture of the top of a blue broth box that is currently closed."
  # - "a VizWiz style picture of a pink 70s style bathroom toilet and tub visible with blue bottles on the toilet tank"
  # - "a VizWiz style picture of a small dog with fluffy tail hair is walking on the patio outside her home near a food bowl."
  # - "a VizWiz style picture of a video conversion system cd in a paper packet with a laminated front covering."
  # - "a VizWiz style picture of a round dial knob on a white washing machine"


model_names:
  - "black-forest-labs/FLUX.2-klein-base-4B"
  - "black-forest-labs/FLUX.1-schnell"
  - "diffusers/FLUX.2-dev-bnb-4bit"
  - "stabilityai/sd-turbo"
  - "stabilityai/sdxl-turbo"
  - "stabilityai/stable-diffusion-xl-base-1.0"

num_inference_steps: 30
seed: 0
output_dir: "results/diffusion_generation"

wandb:
  enabled: false
  project: "c5-week5-diffusion"
  entity: "c5-team2"
  name: "compare-diffusion-models"
