prompts:
  - "a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand."
  - "Some basil leaves in a container on a counter."
  - "a person with a watch that is over a desk with a calendar"
  - "a mac computer screen with a bottle covering part of the screen in the image"
  - "a person is holding a small container of deodorant, the deodorant is branded by the company avon."
  - "a black and white tag listing the specifics of a kitchenaid mixer."
  - "top of a blue broth box that is currently closed."
  - "a pink 70s style bathroom toilet and tub visible with blue bottles on the toilet tank"
  - "a small dog with fluffy tail hair is walking on the patio outside her home near a food bowl."
  - "a video conversion system cd in a paper packet with a laminated front covering."
  - "round dial knob on a white washing machine"

  - "low quality picture of a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand."
  - "low quality picture of Some basil leaves in a container on a counter."
  - "low quality picture of a person with a watch that is over a desk with a calendar"
  - "low quality picture of a mac computer screen with a bottle covering part of the screen in the image"
  - "low quality picture of a person is holding a small container of deodorant, the deodorant is branded by the company avon."
  - "low quality picture of a black and white tag listing the specifics of a kitchenaid mixer."
  - "low quality picture of the top of a blue broth box that is currently closed."
  - "low quality picture of a pink 70s style bathroom toilet and tub visible with blue bottles on the toilet tank"
  - "low quality picture of a small dog with fluffy tail hair is walking on the patio outside her home near a food bowl."
  - "low quality picture of a video conversion system cd in a paper packet with a laminated front covering."
  - "low quality picture of a round dial knob on a white washing machine"
  


reference_images:
  - data/train/VizWiz_train_00000002.jpg # crushed tomatoes
  - data/train/VizWiz_train_00000000.jpg # basil leaves
  - data/train/VizWiz_train_00001014.jpg # watch
  - data/train/VizWiz_train_00002000.jpg # mac computer screen
  - data/train/VizWiz_train_00002006.jpg # deodorant
  - data/train/VizWiz_train_00000358.jpg # kitchenaid tag
  - data/train/VizWiz_train_00002358.jpg # broth box
  - data/train/VizWiz_train_00002357.jpg # bathroom
  - data/train/VizWiz_train_00002355.jpg # dog
  - data/train/VizWiz_train_00002352.jpg # video conversion system
  - data/train/VizWiz_train_00002348.jpg # washing machine
  
  - data/train/VizWiz_train_00000002.jpg # crushed tomatoes
  - data/train/VizWiz_train_00000000.jpg # basil leaves
  - data/train/VizWiz_train_00001014.jpg # watch
  - data/train/VizWiz_train_00002000.jpg # mac computer screen
  - data/train/VizWiz_train_00002006.jpg # deodorant
  - data/train/VizWiz_train_00000358.jpg # kitchenaid tag
  - data/train/VizWiz_train_00002358.jpg # broth box
  - data/train/VizWiz_train_00002357.jpg # bathroom
  - data/train/VizWiz_train_00002355.jpg # dog
  - data/train/VizWiz_train_00002352.jpg # video conversion system
  - data/train/VizWiz_train_00002348.jpg # washing machine


model_names:
  # - "stabilityai/sd-turbo"
  # - "stabilityai/sdxl-turbo"
  # - "stabilityai/stable-diffusion-xl-base-1.0"
  # - "stabilityai/stable-diffusion-3.5-medium"
  # - "stabilityai/stable-diffusion-3.5-large"
  # - "stabilityai/stable-diffusion-3.5-large-turbo"
  - "black-forest-labs/FLUX.2-klein-base-4B"
  - "black-forest-labs/FLUX.1-schnell"
  - "diffusers/FLUX.2-dev-bnb-4bit"

num_inference_steps_by_model:
  # "stabilityai/sd-turbo": 60
  # "stabilityai/sdxl-turbo": 60
  # "stabilityai/stable-diffusion-xl-base-1.0": 60
  # "stabilityai/stable-diffusion-3.5-medium": 60
  # "stabilityai/stable-diffusion-3.5-large": 60
  # "stabilityai/stable-diffusion-3.5-large-turbo": 60
  "black-forest-labs/FLUX.2-klein-base-4B": 5
  "black-forest-labs/FLUX.1-schnell": 5
  "diffusers/FLUX.2-dev-bnb-4bit": 5
  
seed: 0
output_dir: "results/diffusion_generation_flux_5steps"

wandb:
  enabled: false
  project: "c5-week5-diffusion"
  entity: "c5-team2"
  name: "compare-diffusion-models"
