prompts:
  - "a can of crushed tomatoes are on a brown surface, the tomatoes read crushed tomatoes on the brand. Similar in style as the example image provided"

image_prompt: "data/train/VizWiz_train_00000002.jpg"
strength: 0.35

model_names:
  - "stabilityai/sd-turbo"
  - "stabilityai/sdxl-turbo"
  - "stabilityai/stable-diffusion-xl-base-1.0"

num_inference_steps: 30
seed: 0
output_dir: "results/diffusion_generation"

wandb:
  enabled: false
  project: "c5-week5-diffusion"
  entity: "c5-team2"
  name: "image-to-image-compare"
