model_name: "/ghome/group02/Marina/C5-Project/Week5/finetuned_models/sd-flux"
model_type: "blip"
data_dir: "data/"
batch_size: 32
num_workers: 4
val_ratio: 0.1
split_seed: 42
checkpoint: null
output_file: "results/task1/blip-finetuned-sd-flux.json"
max_new_tokens: 30
num_beams: 4

wandb:
  project: "C5-Week5"
  entity: "c5-team2"       
  name: "blip-finetuned-sd-flux-inference"       
  enabled: true 