model_name: "Salesforce/blip-image-captioning-base"
model_type: "blip"
data_dir: "data/"
batch_size: 32
num_workers: 4
val_ratio: 0.1
split_seed: 42
checkpoint: null
#output_file: "results/task1/blip-pretrained.json"
max_new_tokens: 30
num_beams: 4

# training parameters
finetune_encoder: true
finetune_decoder: false
lr_encoder: 1e-5
lr_decoder: 5e-5
weight_decay: 0.01
args.epochs: 30

# logging parameters
wandb:
  project: "C5-Week4"
  entity: "c5-team2"       
  name: "blip-finetuning-encoder"       
  enabled: true 